### ISSUE TITLE
Govee plugin isn't available for MacOS, please add this

### ISSUE THREAD

**Issue by FriendlyCorn** [GeekyEggo/GoveeController#45]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

macOS

### Govee Device

I am waiting for my govee light bar and already got a stream deck plus, I want to use these 2 together

### Bug Description

It is not available for macOS

**Comment by GeekyEggo** [comment]
Hey @FriendlyCorn, good news, support for macOS is available as part of the [the latest beta version](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin). 🙌

**Comment by FriendlyCorn** [comment]
Thank you soooo much!!!
    вторник, 28 марта 2023 г. в 10:59:50 GMT+3, Richard Herman ***@***.***> написал(-а):  
 
 


Closed #45 as completed.

**Comment by GeekyEggo** [comment]
I’d like to add support for dials, although due to API restrictions from Govee, it wouldn’t be possible to reflect the current state of lights, or update them smoothly, e.g. the brightness couldn’t change whilst rotating the dial.

One potential dial is “Brightness” that also enables toggle on/off. The user could turn the dial to determine the brightness, and then press the button to “set” that brightness.

**Comment by FriendlyCorn** [comment]
That’s sad to hear as those dials is game changer, brightness and turn on/off just on 1 dial, I hope one day it becomes possible.

Also wanted to ask you, is there any chance that Govee light bars and other accessories will support HomeKit?
1 апр. 2023 г., 20:08 +0800, Richard Herman ***@***.***>, писал:

**Comment by GeekyEggo** [comment]
It looks as though HomeKit may be possible via [Homebridge](https://homebridge.io/), using the [Homebridge-Govee](https://github.com/bwp91/homebridge-govee) plug-in.
