### ISSUE TITLE
Feature Request: Relative Brightness Adjust

### ISSUE THREAD

**Issue by Jackalneck** [GeekyEggo/GoveeController#57]
Many of the other SD lighting plugins have a "relative brightness" command that changes the current brightness level by a selectable percentage step.  This would allow the user to have  brightness+ and brightness-  keys on their deck to step through brightness levels.  Is it possible to add such a command?

**Comment by GeekyEggo** [comment]
Hey @Jackalneck, thanks for the suggestion. The Govee API currently enforces throttling which limits the number of requests that can be made within a given time frame; this includes requests such as getting the current state of the light, and updating the lights e.g. brightness, on/off, etc. With said throttling in place, dial support would be limited due to;
- Ensuring the brightness bar on the device is correct with continuous (delayed) requests to get the state of a light.
- Updating the device's brightness smoothly when rotating the dial.

Should Govee change this in the future, and ease their throttling rules, I will be more than happy to look into dial support! 😄
