### ISSUE TITLE
A new api is out with new features!

### ISSUE THREAD

**Issue by Fefedu973** [GeekyEggo/GoveeController#63]
https://developer.govee.com/

**Comment by Fefedu973** [comment]
Lighting Products:

In addition to the existing controls for power, brightness, and color, support for the following new features has been added:

• Application of scene modes

• Application of DIYs

• Application of music modes

• Devices with multiple segments will support setting segment colors and toggling the color gradient switch.

• Support for applying snapshots saved on the app As the Govee Development Platform enters its beta version, we invite all users to share their questions and suggestions. Continuous updates and maintenance are in the pipeline to enhance and optimize your experience. We trust you'll love this new platform and achieve your vision of home intelligence.

**Comment by GeekyEggo** [comment]
This is fantastic news; thanks so much for bringing it to my attention @Fefedu973! 🙌

**Comment by Fefedu973** [comment]
> This is fantastic news; thanks so much for bringing it to my attention @Fefedu973! 🙌

Nice ! I have done a small app to demo the api https://github.com/Fefedu973/govee-control-center

**Comment by Fefedu973** [comment]
> This is fantastic news; thanks so much for bringing it to my attention @Fefedu973! 🙌

Nice ! I have done a small app to demo the api if you want to see how it works i haven't added everything and as you can see here there is still a lot of bugs "https://developer.govee.com/discuss". My project: https://github.com/Fefedu973/govee-control-center

**Comment by Cruise105** [comment]
Greetings, more of a question than anything. I just installed the Govee Controller for my Stream Deck and was curious if an update was in the works to allow us to apply scenes to our Govee lights via the Stream Deck. Sorry if this is the wrong place.

**Comment by Ceuse** [comment]
Also a Question (i think it fits here the best) : 

My H608B is not working (missing in the dropdown Menu) - its not listed in the PDF Document but in this list :
https://developer.govee.com/docs/support-product-model

is it just supported in the new API or is something in the Plugin filtering by Product ID?

**Comment by GeekyEggo** [comment]
@Ceuse there is currently an [alpha version](https://github.com/GeekyEggo/GoveeController/raw/nodejs/dist/com.geekyeggo.goveecontroller.streamDeckPlugin) using the new API, I’d be interested to know if your device is visible there.

**Comment by Ceuse** [comment]
@GeekyEggo works perfectly. thank you very much. Now i just need Dreamview to be eventually supported by the API to be completly happy :)

**Comment by Enzobr54** [comment]
@GeekyEggo  

Hello, simply great API to control the lights, congratulations, it works very well with the stream deck. I would like to know if adding a dimmer would be possible, that would be great!! I'm attaching a more meaningful visual example if necessary.

Lower part allows you to decrease and upper part to increase. Some people use this for sound control, I imagine this can be replicated with brightness adjustment?

I also provide an example on the application side where it is possible to choose the quantity to decrease or increase like +/- 5 steps adjustable on the stream deck application
This will make it easier to adjust brightness variations rather than creating a shortcut for 25%/50%/75%/100%
Which forces us to create a shortcut by desired brightness....

Hoping for a possible improvement...
I am waiting with great impatience for your message to respond to me

Good day

(by the way, sorry if I made a mistake in English, it's not my mother tongue, I don't master it perfectly ahaha)

![Example of brightness control](https://github.com/GeekyEggo/GoveeController/assets/160368259/b88a3957-17f9-49b3-a45c-88a25e06157c)

![Stream deck application management example](https://github.com/GeekyEggo/GoveeController/assets/160368259/73e0a974-f0e1-4f66-8be2-2ad0ab06eb24)

**Comment by MartynKeigher** [comment]
Downloaded the alpha plugin last night and it's working great! I can now finally control the bulbs (in my celling) via the Streamdeck! & I love the inclusion of 'Scenes'! 

Also... I don't think the new GoveeAPI allow's for increasing brightness\warmth by a percentage. We may just have to have buttons for each % value, like how you described. (10/25/50/75/100)

**Comment by Fefedu973** [comment]
> Downloaded the alpha plugin last night and it's working great! I can now finally control the bulbs (in my celling) via the Streamdeck! & I love the inclusion of 'Scenes'! 
> 
> Also... I don't think the new GoveeAPI allow's for increasing brightness\warmth by a percentage. We may just have to have buttons for each % value, like how you described. (10/25/50/75/100)

Where did you find this new "alpha" plugin. I don't find it on the GitHub

**Comment by GeekyEggo** [comment]
Thanks for all everyone's patience whilst I look into this — I'm happy to say v1.3 is now available on [Marketplace](https://marketplace.elgato.com/product/govee-controller-ecbbfd1e-6a47-43b3-8056-3aa69d35e8e1), and has been updated to use Govee's new API.

With this update comes [support for more devices](https://developer.govee.com/docs/support-product-model), and should hopefully resolve this issue. Please feel free to raise a new ticket if you encounter any problems. 🚀
